### ISSUE TITLE
Prepare info for common customization and deployment

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#255]
To enable other chain to deploy doa for their use, we will need following info in more explicitly manner to make other life easier

- Recommended way of deployment tracking, how to upgrade, deploy a specific version, etc
- How to connect to their node instance
- How to theme the UI to match their chain look and feel
- How to build a DBJuno with correct historical data

**Comment by rickmak** [comment]
I tried to kick off a local dev and have following road block:

- bdjuno require GENESIS_URL, however the root README does not provide any info on that.
- I key in the skynet info and bdjuno works.
- The react-app is assuming using `likecoin-public-testnet-5`, it come as surprise as default.
- Apparently the react-app setting assumption is not align with the bdjuno assumption.

I try to redo the setup using `likecoin-public-testnet-5` for bdjuno and it keep complaining with `ERROR: failed to start client: websocket: bad handshake`

@hochiw what you think we should do to fix it before asking people to use it.

**Comment by hochiw** [comment]
bad handshake seems like wrong rpc/grpc endpoint for me, but regardless if the db already has information from another chain it has to be wiped first before getting data from other chain in. I can see if we can add such feature to the bdjuno makefile. 

As for the environment alignment do we scrap the default values and let users key in their chain config before they could use the app? or do we use mainnet?

**Comment by hochiw** [comment]
Current testnet bdjuno config
```
        rpc:
            client_name: juno
            address: http://likecoin-public-testnet-5.oursky.dev:26657
            max_connections: 20
        grpc:
            address: likecoin-public-testnet-5.oursky.dev:9090
            insecure: true
```
