### ISSUE TITLE
Update deployment files to support dual chain deployment

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#45]
- Add chain-id to values.yaml
- Deployment name should include chain identifier
- Should include chain name in hostname
etc. `testnet.likedao-dev.pandawork.com` `api.testnet.likedao-dev.pandawork.com` ?
- Update deploy.yaml to handle dual chain deployment using matrix

```yaml
strategy:
      matrix:
        include:
          - chain: "likecoin-public-testnet-5"
            genesisUrl: <testnet_genesis>
          - chain: "likecoin-mainnet-2"
            genesisUrl: <mainnet_genesis>
```
